In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [2]:
df = pd.read_csv('force2020_data_unsupervised_learning.csv',index_col='DEPTH_MD')

In [6]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.dropna(inplace=True)

In [5]:
df

              RHOB         GR      NPHI       PEF         DTC
DEPTH_MD
1138.704  1.774626  55.892757  0.765867  1.631495  147.837677
1138.856  1.800986  60.929138  0.800262  1.645080  142.382431
1139.008  1.817696  62.117264  0.765957  1.645873  138.258331
1139.160  1.829333  61.010860  0.702521  1.620216  139.198914
1139.312  1.813854  58.501236  0.639708  1.504854  144.290085
...            ...        ...       ...       ...         ...
2993.256  2.468236  90.537521  0.341534  4.699200   86.474564
2993.408  2.457519  88.819122  0.351085  4.699200   86.187599
2993.560  2.429228  92.128922  0.364982  4.699200   87.797836
2993.712  2.425479  95.870255  0.367323  5.224292   88.108452
2993.864  2.455546  96.814697  0.379080  6.049967   88.956207

[12202 rows x 5 columns]

In [8]:
scaler = StandardScaler()

we then fit the standard scaler to the data, and then transform our data using that scaler.

In [10]:
df[['RHOB_T','NPHI_T','GR_T','PEF_T','DTC_T']] = scaler.fit_transform(df[['RHOB','NPHI','GR','PEF','DTC']])

In [12]:
df

,RHOB,GR,NPHI,PEF,DTC,RHOB_T,NPHI_T,GR_T,PEF_T,DTC_T
DEPTH_MD,,,,,,,,,,
1138.704,1.774626,55.892757,0.765867,1.631495,147.837677,-1.491843,2.523654,-0.179292,-1.255364,0.869531
1138.856,1.800986,60.929138,0.800262,1.645080,142.382431,-1.387067,2.770744,-0.010859,-1.247886,0.690042
1139.008,1.817696,62.117264,0.765957,1.645873,138.258331,-1.320646,2.524300,0.028875,-1.247450,0.554350
1139.160,1.829333,61.010860,0.702521,1.620216,139.198914,-1.274390,2.068584,-0.008126,-1.261572,0.585297
1139.312,1.813854,58.501236,0.639708,1.504854,144.290085,-1.335919,1.617342,-0.092056,-1.325067,0.752808
...,...,...,...,...,...,...,...,...,...,...
2993.256,2.468236,90.537521,0.341534,4.699200,86.474564,1.265151,-0.524699,0.979338,0.433103,-1.149449
2993.408,2.457519,88.819122,0.351085,4.699200,86.187599,1.222550,-0.456081,0.921870,0.433103,-1.158891
2993.560,2.429228,92.128922,0.364982,4.699200,87.797836,1.110101,-0.356250,1.032560,0.433103,-1.105910
2993.712,2.425479,95.870255,0.367323,5.224292,88.108452,1.095199,-0.339430,1.157682,0.722114,-1.095690
2993.864,2.455546,96.814697,0.379080,6.049967,88.956207,1.214709,-0.254974,1.189267,1.176566,-1.067797

In [13]:
def optimise_k_means(data,max_k):
    means = []
    inertias = []
    for k in range(1,max_k):
        kmeans = KMeans(n_clusters=k)
        kmeans.fit(data)
        
        means.append(k)
        inertias.append(kemans.inertia_)
    #generate the elbow plot
    fig = plt.subplots(figsize=(10,5))
    plt.plot(means,inertias,'0-')
    plt.xlabel('Number of Clusters')
    plt.ylabel('Inertia')
    plt.grid(True)
    plt.show()

In [16]:
optimise_k_means(df[['RHOB_T','NPHI_T']],10)

KeyError: "['HPHI_T'] not in index"